### PR TITLE
Added IntlConsumer component

### PR DESCRIPTION
**Pull request by artalat**
Converts the `injectIntl` hoc to `IntlConsumer` component to support render prop pattern.

### Sample Code

```javascript
<BR.Components.IntlConsumer>
{(intl) => {
	// console.log('do something with the intl object here');
}}
</BR.Components.IntlConsumer>
```

### CODE REVIEW

**Comment by artalat** [comment]
@bjavaid this needs to be updated to use `bluerain build plugin` command instead of building with rollup directly. Needs updates to the dependencies including sematic release. i wonder if merging without that would work. 🤔

**Comment by bjavaid** [comment]
Packages modified as the latest releases.

**Pull request merged**
